In [42]:
from sklearn.datasets import load_wine
#digits = load_digits()
wines = load_wine()
print( type(wines))

<class 'sklearn.utils.Bunch'>


In [43]:
print( wines.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [44]:
print(wines.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [45]:
print( type(wines.data))
print( wines.data.shape)
print(wines.target.shape)
print(wines.data[0].shape)
print(wines.data[0])

<class 'numpy.ndarray'>
(178, 13)
(178,)
(13,)
[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]


In [46]:
print(wines.target_names)
print(wines.target)

['class_0' 'class_1' 'class_2']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [47]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(wines.data)
winesstandardized = scaler.transform(wines.data) 

pdstdscaled =pd.DataFrame(winesstandardized)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split( wines.data,
                                                 wines.target,
                                                 test_size= 0.40)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(106, 13) (106,) (72, 13) (72,)


In [48]:
from sklearn import linear_model

logistic = linear_model.LogisticRegression( solver='lbfgs',max_iter = 2000,multi_class = 'multinomial')

In [49]:
logistic.fit(x_train,y_train)
print( 'score: ' , 100*logistic.score(x_test,y_test),'%')

score:  94.44444444444444 %


In [50]:
ypred_test = logistic.predict(x_test)
print(ypred_test)

[1 2 1 2 0 0 1 0 1 0 0 2 0 0 0 0 0 2 0 1 2 1 2 1 2 1 0 0 1 1 1 0 0 1 2 2 1
 0 0 1 2 0 0 2 1 1 1 2 2 0 0 1 1 0 1 0 1 2 1 2 0 0 2 2 1 2 1 1 1 0 1 0]


In [51]:
for i in range ( len(y_test)):
    if ( y_test[i] != ypred_test[i]):
        print(i,y_test[i],ypred_test[i])

36 2 1
45 0 1
52 0 1
62 1 2


In [52]:
print("classes", logistic.classes_)
print("Total feature weights", logistic.coef_.shape)
print(" Total bias weights",logistic.intercept_.shape)
print("Total iterations", logistic.n_iter_)

classes [0 1 2]
Total feature weights (3, 13)
 Total bias weights (3,)
Total iterations [1884]


In [53]:
ypred_logproba = logistic.predict_log_proba(x_test[0:2])
print(ypred_logproba)
ypred_proba  = logistic.predict_proba(x_test[0:2])
print("  ")
print(ypred_proba)

[[-5.66659174 -0.06046915 -2.89647427]
 [-5.02146713 -3.68831225 -0.03211938]]
  
[[0.00345964 0.9413228  0.05521756]
 [0.00659484 0.02501418 0.96839097]]


In [54]:
help (logistic)

Help on LogisticRegression in module sklearn.linear_model._logistic object:

class LogisticRegression(sklearn.base.BaseEstimator, sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin)
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', 'sag', 'saga' and 'lbfgs' solvers. **Note
 |  that regularization is applied by default**. It can handle both dense
 |  and sparse input. Use C-ordered arrays or CSR matrices containing 64-bit
 |  floats for optimal performance; any other input format will be con