In [1]:
a = [1,0,0]

In [2]:
print(a)
print(type(a))

[1, 0, 0]
<class 'list'>


In [3]:
a = [ 1,0,"hello","world",0x2345]
print(a)
print(type(a))


[1, 0, 'hello', 'world', 9029]
<class 'list'>


In [4]:
3+4


7

In [5]:
import numpy as np
a = np.array( [1,0,0,2])


In [6]:
print(a)

[1 0 0 2]


In [8]:
print(type(a),a.dtype)


<class 'numpy.ndarray'> int32


In [10]:
a = np.array([ [1,0,0],[0,1,1]])

In [11]:
print(a)

[[1 0 0]
 [0 1 1]]


In [13]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [15]:
a = np.zeros( (3,3,3,3,3))

In [16]:
print(a)

[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]

In [17]:
print(a.dtype)

float64


In [18]:
print(a.ndim)

5


In [19]:
print(a.shape)

(3, 3, 3, 3, 3)


In [25]:
print(a.size)

243


In [26]:
print(a.dtype)

float64


In [28]:
a = np.arange( 10 , 30 , 4 )

In [29]:
print(a)


[10 14 18 22 26]


In [30]:
a = np.linspace(0,2,9)

In [31]:
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [33]:
ar = np.random.random_integers(5,size=(2,3))
br = np.random.random_integers(2,size=(3,2))
cr = np.random.random_integers(2,size=(2,3))
print(ar)
print(br)
print(cr)
print("ar*cr=",ar * cr)
print("ar @ br",ar ,ar.dot(br))   

[[2 4 2]
 [2 5 2]]
[[1 2]
 [2 2]
 [2 1]]
[[2 2 2]
 [2 2 1]]
ar*cr= [[ 4  8  4]
 [ 4 10  2]]
ar @ br [[2 4 2]
 [2 5 2]] [[14 14]
 [16 16]]


C:\ProgramData\Anaconda3\envs\IT1602-17-737-114\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\envs\IT1602-17-737-114\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  
C:\ProgramData\Anaconda3\envs\IT1602-17-737-114\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [34]:
print(ar.sum())

17


In [35]:
print(br.sum())

10


In [36]:
print(cr.sum())


11


In [38]:
print(ar.max(axis=0),ar.max(axis=1))

[2 5 2] [4 5]


In [39]:
a3r = np.random.random_integers(5,size=(2,3))

C:\ProgramData\Anaconda3\envs\IT1602-17-737-114\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """Entry point for launching an IPython kernel.


In [40]:
print(ar)

[[2 4 2]
 [2 5 2]]


In [45]:
for i in ar:
    print(i)

[2 4 2]
[2 5 2]
